######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 13 21:39:13 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += cache.cpp
