######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 8 15:01:28 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += myslider.cpp
