######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 29 16:09:40 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h myglwidget.h myglgraph.h
SOURCES += main.cpp mainwindow.cpp myglwidget.cpp myglgraph.cpp

QT += opengl